### ISSUE TITLE
Links from source sheet not coming through to popups on map

### ISSUE THREAD

**Issue by neuhausr** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#134]
Noticed some of the links from the spreadsheet are not appearing in the popup info. For example, for the Sheraton Hotel Midtown Sanctuary, the Accepting column has a link to their Google Sheet, but that is stripped out in the popup so on the map, you can't see where to link to. In other cases, it's less of an issue because the actual URL is listed in your source sheet.

This could be fixed by always including the URL so users can cut and paste it, or it would probably be ideal to have URLs in the popups be clickable.

**Comment by crhistianramirez** [comment]
It actually looks like no links are captured because we're extracting google sheets content as JSON. The links for addresses are actually built up from the address itself rather than from any links defined on google sheets. For example:

```html
<a href="https://maps.google.com?saddr=Current+Location&daddr=${encodeURI(address)}" target="_blank">${address}</a>
```

For the short term it may be easiest to simply have entries include the actual link so that users can at least copy/paste that into their browser, however it would be ideal if we could handle that transparently. 

One possible solution might be to add a script similar to the one that we have for [google addresses](https://github.com/mc-funk/community-map-google-scripts/) which works by monitoring changes to the address column, and writing lat/long to their own columns. Instead, we'd monitor changes to any column and if it has links capture them and write them to a new "hyperlinks" column.

I honestly don't love that solution, I can see it getting messy and error prone. I'd love to hear if anybody has alternative suggestions on how to solve
