### ISSUE TITLE
Ensure language choices are tracked by Google Analytics

### ISSUE THREAD

**Issue by andyinabox** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#154]
There is language information in the Google analytics data, but I want to make sure the users' language choice in our UI is being accurately captured there. Feel free to close this issue if you've already investigated.

**Comment by echoseekererer** [comment]
On my radar. This is contingent upon GTM implementation/access for this property (in progress) and probably some dev work (tbd).

**Comment by experimatt** [comment]
This seems related to https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/issues/178.

I just poked around in GA and found two different ways of viewing language info. Screenshots below for reference.

**Browser Languages**
<img width="759" alt="Screen Shot 2020-06-23 at 8 30 35 PM" src="https://user-images.githubusercontent.com/2946681/85489586-d2d2b400-b595-11ea-8b9e-651fc38d949c.png">

**Language Changed Events**
![image](https://user-images.githubusercontent.com/2946681/85489540-c189a780-b595-11ea-9396-08f3f760ec39.png)

**Comment by echoseekererer** [comment]
> This seems related to #178.
> 
> I just poked around in GA and found two different ways of viewing language info.

@experimatt Correct! We are tracking languages via browser default (first screenshot) and events (second screenshot). However, I don't think this is giving us an accurate picture of how users are interacting with the menu. It currently fires even if users have not selected the option (like if they refresh the page or come back to the page later in the same browser session, but a different tab), which is useful info, but viewed in the context of "how many users do we have that are selecting a different language," the results are skewed, even when selecting for "Unique Events."

I'm not sure what the triggers are for the event tracking on this currently, but I think they may need to be tweaked (per #178) to account for these instances.

**Comment by Dthurow** [comment]
This ticket looks to be just verifying that language changes are being tracked in google analytics, and I'm currently working on #178, which is modifying that functionality. Once I'm done with #178 I'll be able to definitely say we are tracking language changes in GA and can do a short write up explaining when/how it's tracking it and where to find it in GA, then probably close this issue.

**Comment by Dthurow** [comment]
Since the changes are merged into master, I can  say for sure the current functionality:
User's language choice in the UI (In the "welcome" popup where you select your language) is tracked when the user first hits the website and actively selects a language, and every other time they open the language popup and choose a different language.

Before #178, it also triggered a "language_change" event every time a user loaded the page, because the code was setting the language option by looking at what the user had selected earlier. That no longer happens.

To see the events in Google analytics:
On the home page, go to Events->Overview. Select "Event Action", then the "language_change" event
![Get to language_change](https://user-images.githubusercontent.com/3959067/100891864-5797f700-347f-11eb-813d-98fa7271745c.png)
To see the individual languages users are selecting, click on the "Event Label" button
![see individual languages chosen](https://user-images.githubusercontent.com/3959067/100892052-8ada8600-347f-11eb-9d8c-35c448f85237.png)
You can then see the number of times users have selected the individual languages for the given time frame
![Language event labels](https://user-images.githubusercontent.com/3959067/100892113-98900b80-347f-11eb-90d6-b758d2d79669.png)

Unless there are other questions about this, I think this ticket can be closed.
