### ISSUE TITLE
site-wide disclaimer about covid-19 safety

### ISSUE THREAD

**Issue by estherrose046** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#161]
We need some way of alerting all of our users that we are still living in Pandemic times, and to observe precautions! At this point we are encouraging people to go into possibly crowded public spaces and want to re-center the health risks posed by covid-19. 

There should be some way to alert all users about this disclaimer

**Comment by drewsteff** [comment]
Do we want to have this as a general alert/text in a spot on the site that is fixed/stays visible? I can make a quick render and see what you guys think?

**Comment by drewsteff** [comment]
Here's an idea for the alert and a reminder message

<img width="1440" alt="COVID Alert - Wireframe (1)" src="https://user-images.githubusercontent.com/66445081/84575527-48a77600-ad73-11ea-9245-8c54375f55fd.png">

**Comment by drewsteff** [comment]
Here's an idea for the alert and reminder message

<img width="1440" alt="COVID Alert - Wireframe" src="https://user-images.githubusercontent.com/66445081/84575580-acca3a00-ad73-11ea-812b-3e5ed897f541.png">

**Comment by drewsteff** [comment]
Mobile Version:

<img width="377" alt="Mobile Version - COVID-19 Alert" src="https://user-images.githubusercontent.com/66445081/84575815-b6ed3800-ad75-11ea-8ef9-633d3316fa42.png">

**Comment by estherrose046** [comment]
@drewsteff this is amazing! I love where you went with this and also the conversation on slack!

A few minor things - I think the three yellow circles should all be the same size, and if its possible to do this without taking up too much screen real-estate maybe add a titch more padding around the circle icons.

**Comment by drewsteff** [comment]
@estherrose046 

Here's what I have come up with so far. 

I made a mobile sized rendering of the covid alert with the revised sizing of the circles/icons and padding you were mentioning (good calls all around thank you!).

I also added a link for the MN department of health to refer people if they need more info

There are essentially three options for the icon colors/consistency and I'll post all three but just use one in the example of the entire mobile screen.

Let me know what else would be needed from my end, otherwise I think we can decide on one and I can make a desktop size version if that works or we can just use that one for now as a responsive size design and not include any additional text on the desktop size version.

[Mobile Covid Alert.pdf](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/files/4776624/Mobile.Covid.Alert.pdf)


Other icon options- 

[Icon V1 Covid Alert - Mobile Size.pdf](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/files/4776626/Icon.V1.Covid.Alert.-.Mobile.Size.pdf)


[Icon V2 Covid Alert - Mobile Size.pdf](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/files/4776627/Icon.V2.Covid.Alert.-.Mobile.Size.pdf)



Original one on it's own-

[mobile covid alert bar.pdf](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/files/4776629/mobile.covid.alert.bar.pdf)
