### ISSUE TITLE
Links in Google Sheet renders incorrectly on map

### ISSUE THREAD

**Issue by emyl3** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#169]
The current implementation of creating `<a>` links on the map is causing an issue when rendering out Google sheet entries that have a clickable link in the cell.

An example is the "Notes" section of "The Sheridan Story".
<img width="1236" alt="Screen Shot 2020-06-13 at 8 48 51 PM" src="https://user-images.githubusercontent.com/20211771/84582885-8fb75a80-adb7-11ea-897d-34901e36d9dd.png">

My bad for introducing this bug in [PR 168](https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/168)

**Comment by emyl3** [comment]
I am wondering if this is just limited to this particular entry for "The Sheridan Story" because all other inline links within Google Sheets just don't render at all since we aren't getting the HTML data from google sheets (i believe) 🤔

**Comment by estherrose046** [comment]
Update to this issue:

There is still an issue with the regex for links, because currently if a URL ends in a comma or other punctuation, i.e. "http://www.google.com," the comma gets sucked into the link and it fails.

**Comment by emyl3** [comment]
@estherrose046 Thank you for pointing that out! 😸 

Maybe the regex could avoid capturing punctuations (e.g. periods, commas, semicolons, etc..) after the final `.` of the url?

I was suppose to write some unit tests for the regex but haven't had the time to start it this week. I'll create an issue for unit testing the regex so that I don't forget about it or if someone has the capacity to get to it before I do -- they can totally do so. 😅

**Comment by TimothyMDean** [comment]
@emyl3 It looks like the Regex was taken from [one specific answer](https://stackoverflow.com/a/17773849) to the SO question you linked to in the code. The comments on that answer specifically mention a problem with trailing punctuation marks, and the regex’s author doesn’t provide a good answer to that problem.

Getting a regex to match all URLs is a notoriously hard problem to get right, which is why there are so many different SO answers out there. But following the question you linked to in the code, I found that it referenced [this question](https://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url), and the highest-upvoted answer there was [this one](https://stackoverflow.com/a/190405)
