### ISSUE TITLE
Language translations

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#40]
From Eileen:
> A major barrier to access right now is English language. We're working on sourcing some help with figuring out whether Google Translate is accurate enough to be useful and for sure at least translating the column headings, legend, and other things that are more or less static, but if someone on the dev side could start thinking sooner rather than later about how to change the interface to make language switching easy and obvious, that would be great. Languages we're shooting for are currently Spanish, Somali, Hmong, and Karen; open to other suggestions.

**Comment by experimatt** [comment]
This has potential be a very large task, and will require some research in advance

**Comment by experimatt** [comment]
Update from Eileen:
>I think the direction translation is moving is just having human translations done for the static labels and deciding the rest is (at least currently) beyond the scope of what we can handle. Even having language options for the map legend would be a huge asset - someone with limited English is going to get stuck at the word "distribution." If they can tell what the colors mean and then tap map dots to see hours, that's a LOT more information than is currently accessible

With that, the scope of this task just got a lot smaller. Localizing the text in the legend/title area and where we're labelling things in map markers should be manageable

**Comment by andyinabox** [comment]
I'll jump on this tonight if nobody else has by then

**Comment by andyinabox** [comment]
I'm going to do a bit more research on this, but I'm currently thinking we might just be better off rolling our own simple solution since most tools out there are pretty complex. Some assumptions/considerations I'm considering:

 - I think to stay consistent with our accessible workflow translations should be done in a Google Sheet
 - I'm working under the assumption we will do targeted translations of things like labels and probably won't be able to translate most of the data for the time being

Here's what I'm planning:

1. I expect to use a Google Sheet with a row for each term and columns for each language. Here's an example: https://docs.google.com/spreadsheets/d/1m5QPNP6O8nsQsqJcQbwib_obpXRjmbYYGtwKzzg1l38/edit?usp=sharing

2. Fields that have translations will use the attribute `data-translation-id` (or something similar) to identify which translation they correspond to. Example:

```html
<span data-translation-id="hello">Hello!</span>
```

3. Use a querystring variable to set language, for instance `https://twin-cities-mutual-aid.org/?lang=som`

4. After loading the Google sheet data, gather all the elements with `data-translation-id` and check to see if the language is something other than English. Then for each of those, replace text with translation if found.

I welcome any comments or suggestions!

**Comment by hinzed1127** [comment]
I agree, I spent some time looking over a few different solutions and agree a minimal self-made might be the best approach, especially since these labels shouldn't change too much over time.

The only thing I see in those steps as a possible enhancement is using [browser APIs](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/languages) to see if someone has a different language set, in which case we could default to that.

Otherwise, you're pretty much describing the exact same process that [this person took](https://codeburst.io/translating-your-website-in-pure-javascript-98b9fa4ce427).
