### ISSUE TITLE
Filter by needs

### ISSUE THREAD

**Issue by experimatt** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#42]
From Michelle:
> Priorities we’re hearing from volunteers/users include:
• Being able to filter side list by need

I'm not sure if that means filtering on the "Urgent Needs" field, the "Accepting", or both. Waiting on clarification here.

**6/6/20 Update:** The big picture goal here is to make it possible for visitors to search/filter on the site by receiving/donation items. The working assumption is that we'll need to search across both the "urgent needs" and "accepting" fields.

**Comment by jasonthibeault** [comment]
I would suspect having the ability to type in a need keyword and having the list filter to only those containing that need would suffice for this. Would have to work in tandem with the filter checkboxes.

**Comment by experimatt** [comment]
@jasonthibeault yeah as soon as there are multiple different ways to filter on the page it'll start to get confusing. I like the idea of a type-ahead keyword list, too, if we've got data structured in a way to support it. Good call!

**Comment by andyinabox** [comment]
@jasonthibeault @experimatt I know that the lib I used for sorting (https://github.com/javve/list.js) has search capability. I'm not 100% certain but I think if we added a hidden field to the cards with all needs listed, then we could make it searchable pretty easily

**Comment by lbarhaugh** [comment]
My understanding is the same as Jason's: As a user, I want to filter results by need so that I can see who needs what I have. 

Basically a slightly fancier "find" function.

**Comment by drewsteff** [comment]
Are these going to be labels or categories for locations that are filtered, or rather locations have 'tags' listed on the pop up, allowing users to then search the tags?

**Comment by lbarhaugh** [comment]
@drewsteff here are the user stories:

As a user, I want to filter to locations accepting what I have, so that I can see where to take my supplies.

As a user, I want to filter to locations that have what I need, so that I can see where to pick up supplies.

Still learning what yall call everything, but what we're going for is, for example, I can type in the word "hygiene" and this location would come up:

<img width="442" alt="Screen Shot 2020-06-06 at 2 16 59 PM" src="https://user-images.githubusercontent.com/47987237/83952739-65d2c680-a800-11ea-96e6-ae7411339d89.png">

**Comment by experimatt** [comment]
Is this done with the addition of fuzzy search? If so, can we close?

**Comment by amaxama** [comment]
Closing this issue as I believe we have the functionality requested currently on the site. Feel free to re-open if I missed something!
