### ISSUE TITLE
Hide "confirmed closed" locations by default

### ISSUE THREAD

**Issue by kmarekspartz** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#51]

**Comment by kmarekspartz** [comment]
Not sure what the intent of the confirmed closed status is, is this permanent or temporarily closed? May need a different status.

Based on how I interpreted it, here's how I would expect the page to load:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/969868/83701242-ae0aa280-a5ce-11ea-817b-a971857c39aa.png">

**Comment by jdalt** [comment]
Confirmed closed are locations that are currently not open -- it's a realtime status indicator. "confirmed closed" might not be the correct language. Maybe the meaning is more accurately "currently closed". Of course this is different from "status unknown" where no hours are understood.

I think it's a good idea to interrogate our defaults here and ask what are priorities are. I've often wondered whether "Urgent Needs" is the sort order that should be prioritized first. These are important usability questions and they get to the heart of this fog we have -- are we serving the distributors of aid or the recipients of aid first on this map?

I'm guessing we are biased towards the distributors since we ourselves are effectively distributors. Some sort of open analytics and feedback would be useful here, but in the absence of that I would like to challenge someone to come up with a point of view on what good defaults look like.

**Comment by kmarekspartz** [comment]
Some people might be both, e.g. “I have medicine but need infant formula”, not in a barter perspective but in a looking for both. I think a single UI makes sense for both pickup and drop off. Perhaps typeahead filtering is they way to go then?

–
Kyle Marek-Spartz

**Comment by experimatt** [comment]
This was covered by https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/71, along with "unknown status" locations
