### ISSUE TITLE
The default state is show Open Places, at night the map/list is empty

### ISSUE THREAD

**Issue by caseyhelbling** [Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations#80]
Ideally, we could handle the empty state better. But as a compromise maybe add the counts places next to each filter option.

![2020-06-04 at 11 53 PM](https://user-images.githubusercontent.com/12005/83838685-8e06dc00-a6bf-11ea-88c3-9c544b5ffe6b.png)

**Comment by estherrose046** [comment]
This issue was addressed in https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/129 and https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/163 and https://github.com/Twin-Cities-Mutual-Aid/twin-cities-aid-distribution-locations/pull/118. Closing now
